### ISSUE TITLE
Different version depending on system language

### ISSUE THREAD

**Issue by SFGrenade** [homothetyhk/HollowKnight.LoadNormalizer#1]
https://github.com/homothetyhk/HollowKnight.LoadNormalizer/blob/0deb16afa2950ca82afa712f3f48265b708bde68/LoadNormalizer/LoadNormalizer.cs#L58-L61

this converts the float to a string, but depending on the system language it can convert it to either "1.2" or "1,2".
suggestion:
```cs
return LoadTimes.defaultLoad.ToString("G", CultureInfo.InvariantCulture);
```

**Comment by homothetyhk** [comment]
Closed by [e87ea0d](https://github.com/homothetyhk/HollowKnight.LoadNormalizer/commit/e87ea0dc23df98c3278191415e45fd4237322008).
